import { StrictMode } from 'react'
import { createRoot, hydrateRoot } from 'react-dom/client'
import { BrowserRouter } from 'react-router-dom'
import './index.css'
import App from './App'

const container = document.getElementById('root')!

const tree = (
  <StrictMode>
    <BrowserRouter>
      <App />
    </BrowserRouter>
  </StrictMode>
)

// Every canonical route is prerendered to static HTML at build time, so the
// normal path is hydration. createRoot is the fallback for a document that was
// served without prerendered markup.
if (container.hasChildNodes()) {
  hydrateRoot(container, tree)
} else {
  createRoot(container).render(tree)
}

/**
 * Register the service worker generated by scripts/prerender.mjs.
 *
 * It precaches the app shell and serves a branded offline page. It never caches
 * API responses, so going offline means "no estimate" rather than a stale
 * estimate presented as current (audit issue P1-15).
 */
if ('serviceWorker' in navigator && import.meta.env.PROD) {
  window.addEventListener('load', () => {
    navigator.serviceWorker.register('/sw.js').catch((error: unknown) => {
      console.warn('Service worker registration failed:', error)
    })
  })
}
